mini: parser.tab.c lex.yy.c ast.o main.o
	gcc -Wall -Wextra -g -o mini parser.tab.c lex.yy.c ast.o main.o

parser.tab.c: parser.y
	bison -d parser.y

lex.yy.c: scanner.l
	flex scanner.l

ast.o: ast.c ast.h
	gcc -c ast.c

main.o: main.c ast.h
	gcc -c main.c

clean:
	rm -f *.o mini parser.tab.* lex.yy.c

